name: deploy-docs

on:
  push:
    tags:
       - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: setup node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: install deps
      run: |
        git config --global user.name "chris (deploy pipline)"
        git config --global user.email "chris@bumblehead.com"
        npm ci
      env:
        CI: true

    - name: deploy docs
      run: |
        npm run deploy
      env:
        CI: true
