name: test-component

on: [push, pull_request_target]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup node 14.x
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: test
      run: |
        yarn install
        yarn build
        yarn test
      env:
        CI: true
