name: test-component

on: [push, pull_request_target]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: setup node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
